name: optimized-clustering
channels:
  - conda-forge
  - nvidia
  - defaults
channel_priority: strict
dependencies:
  - python=3.12
  - cudatoolkit=11.8
  - pandas
  - numpy
  - scikit-learn
  - spacy
  - nltk
  - tensorflow-gpu=2.19.0
  - pytorch=2.6.0
  - torchvision
  - torchaudio
  - cupy
  - pip
  - pip:
      - sentence-transformers
      - langdetect
      - tf-keras
